version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: IncidentsDB
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=aws-0-us-east-1.pooler.supabase.com;Port=5432;Database=IncidentsDB;Username=postgres.pnjupdzomswcqkrzuycv;Password=eNJM9hEEyhD9Jyqy;
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./TicketFrontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "7070:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
